[package]
name = "hawk-pack"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
sqlx = { version = "0.7", features = [ "runtime-tokio", "postgres" ] }
tokio = { version = "1.38.0", features = ["full"] }
